POST https://learn-fastify.onrender.com/cars
Content-Type: application/json

{
    "brand": "Ford",
    "model": "Mustang Boss 429"
}


// Separador de requisições
###

GET https://learn-fastify.onrender.com/cars

###

PUT https://learn-fastify.onrender.com/car/2
Content-Type: application/json

{
    "brand": "Ford",
    "model": "Mustang 1978"
}

###

DELETE https://learn-fastify.onrender.com/car/1


